spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2023code9
    password: vtopxrovdrchqzdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8083
