insert into person(id, name, surname, address, username, age, score) values (1, 'Ivan', 'Ivanovic', 'Beogradska 12', 'ivani', 20, 100);
insert into person(id, name, surname, address, username, age, score) values (2, 'Petar', 'Petrovic', 'Svetosavska 11', 'petarp', 31, 88);
insert into person(id, name, surname, address, username, age, score) values (3, 'Ana', 'Jovanovic', 'Zeleznicka 8', 'anaj', 25, 95);
insert into person(id, name, surname, address, username, age, score) values (4, 'Zorana', 'Zoric', 'Kisacka 3', 'zoranaz', 19, 81);
insert into person(id, name, surname, address, username, age, score) values (5, 'Ivana', 'Acimovic', 'Gunduliceva 33', 'ivanaa', 33, 100);
insert into person(id, name, surname, address, username, age, score) values (6, 'Nenad', 'Nenadovic', 'Slovacka 41', 'nenadn', 34, 77);
insert into person(id, name, surname, address, username, age, score) values (7, 'Pavle', 'Pavlovic', 'Pavla Papa 7', 'pavlep', 19, 99);
insert into person(id, name, surname, address, username, age, score) values (8, 'Aleksandra', 'Aleksic', 'Majevicka 1', 'aleksandraa', 26, 79);
insert into person(id, name, surname, address, username, age, score) values (9, 'Natalija', 'Borisavljevic', 'Kopernikova 16', 'natalijab', 19, 91);
insert into person(id, name, surname, address, username, age, score) values (10, 'Filip', 'Filipvic', 'Suboticka 22', 'filipf', 22, 75);