spring:
  application:
    name: monolithic-app
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2023code9
    password: vtopxrovdrchqzdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation : true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081
