services:
  discovery:
    build: discovery
    container_name: discovery-service
    image: levinine/codenine/discovery
    ports: 
    - "8761:8761"
  library:
    build: library
    container_name: library-service
    image: levinine/codenine/library
    ports:
      - "10001:8080"
    depends_on:
      - discovery
    entrypoint: 
      - "java"
      - "-jar"
      - "-DEUREKA_SERVER=http://discovery-service:8761/eureka"
      - "app.jar"
  gateway:
    build: gateway
    container_name: gateway-service
    image: levinine/codenine/gateway
    ports:
      - "10002:8080"
    depends_on:
      - discovery
    entrypoint: 
      - "java"
      - "-jar"
      - "-DEUREKA_SERVER=http://discovery-service:8761/eureka"
      - "app.jar"

networks:
  codenine-eureka:
    driver: build
